name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Mude para sua branch principal se necessário
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # ou a versão que você está usando

      - name: Install dependencies
        run: npm install
        working-directory: ./client  # Indica o diretório da aplicação

      - name: Build
        run: npm run build
        working-directory: ./client  # Indica o diretório da aplicação

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'  # para implantações de produção
          working-directory: ./client  # Indica o diretório da aplicação